# https://github.com/marketplace/actions/auto-merge-pull-request
name: Automerge
on:
  # Try merging a pull request when it is approved.
  pull_request_review:
    types:
      - submitted
  # Try merging pull requests belonging to a workflow run.
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          do-not-merge-labels: no-automerge
          pull-request: ${{ github.event.inputs.pull-request }}
