# https://github.com/marketplace/actions/auto-merge-pull-request
name: Automerge
on:
  schedule:
    - cron: 0 * * * *
      
jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          do-not-merge-labels: no-automerge
          pull-request: ${{ github.event.inputs.pull-request }}
